### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by joakimwinum** [Gadgetoid/dir2uf2#2]
I noticed your repository doesn't have a license. It would be great if you could add one to clarify permissions for use and contributions. Here's a helpful tool to choose the right one: https://choosealicense.com/.

**Comment by Gadgetoid** [comment]
Hello hello hello. What caused you to stumble here? 😆 

Fixed - https://github.com/Gadgetoid/dir2uf2/blob/main/LICENSE

**Comment by joakimwinum** [comment]
Hi, thank you for adding a license so quickly. I am working on upgrading Enviro MicroPython firmware to the latest Pimoroni Pico Libraries to solve some SSL issues I encountered with Let's Encrypt TLS certificates, and found this repository as a building step in the GitHub Action workflow.

**Comment by Gadgetoid** [comment]
Just a word of warning- LittleFS Python had a 0.5.0 release with a LittleFS version bump making it incompatible with Pico MicroPython. You will need to install, specifically, v0.4.0-

```
python3 -m pip install littlefs-python==0.4.0
```
