### ISSUE TITLE
Read flash drive from .uf2 `bi_decl` region

### ISSUE THREAD

**Issue by Gadgetoid** [Gadgetoid/dir2uf2#3]
As mentioned here - https://github.com/micropython/micropython/pull/12357 - it occurred to me that we could probably read the flash offsets from the .uf2 file rather than hard-coding them into the CI.

@daft-freak I don't suppose you had Python code somewhere to delve into Pico `bi_decl` stuff?

**Comment by Daft-Freak** [comment]
:thinking: Not in Python. There's some [code in DERP](https://github.com/Daft-Freak/DERP/blob/main/minsdl/Main.cpp#L80), but that unpacks the whole thing first. Should be another parser in the blit discord bot, but I think that's JavaScript.

**Comment by Gadgetoid** [comment]
Close enough, I'll figure it out when I find a moment to try this :laughing:

**Comment by Daft-Freak** [comment]
Oh, this is the bot's code (might help as I don't think I released the code anywhere): https://gist.github.com/Daft-Freak/63e2f3ff052ba89a0de239c66671617

Attempts to parse UF2 as it goes. Still only handles string tags though.

**Comment by Gadgetoid** [comment]
Fixed in #7
